name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Jalankan setiap hari pada tengah malam UTC
  workflow_dispatch: # Memungkinkan untuk menjalankan action secara manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: denaeyaa # Pastikan ini username GitHub-mu
          outputs: | # Perhatikan indentasi ini (sejajar dengan 'github_user_name')
            dist/github-contribution-grid-snake.svg # Ini harus diindentasi 2 spasi dari 'outputs: |'
            dist/github-contribution-grid-snake-dark.svg # Ini juga harus diindentasi 2 spasi dari 'outputs: |'
          color_snake: '#a7d95e' # Warna ular (hijau terang dari sebelumnya)
          color_dots: '#161b22,#0e4429,#006d32,#26a641,#39d353' # Gradasi dari hitam ke hijau
          background: '#161b22' # Latar belakang sangat gelap
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # Branch tempat snake.svg akan disimpan
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
