name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Jalankan setiap hari pada tengah malam UTC
  workflow_dispatch: # Memungkinkan untuk menjalankan action secara manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: platane/snk@v3
        with: # <-- Ini adalah level indentasi yang benar untuk 'with'
          github_user_name: denaeyaa # Pastikan ini username GitHub-mu
          outputs: | # <-- Indentasi 2 spasi dari 'with'
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          color_snake: '#a7d95e' # <-- Indentasi 2 spasi dari 'outputs' atau 'github_user_name'
          color_dots: '#186338,#33a753,#8cd36e,#bddf7e,#e1f38a'
          background: '#161b22'
        env: # <-- Ini sejajar dengan 'with'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # Branch tempat snake.svg akan disimpan
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
