name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: platane/snk@v3
        with:
          github_user_name: denaeyaa
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark # <-- Cukup ini saja untuk versi gelap
            # Jika kamu ingin juga versi terang untuk pengguna tema terang:
            # dist/github-contribution-grid-snake-light.svg?palette=github-light
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
